### ISSUE TITLE
.jar doesn't end up in plugins folder

### ISSUE THREAD

**Issue by kdmarchuk** [NicoKiaru/LimeSeg#13]
Hello, 
Following the method as directed here: https://imagej.net/LimeSeg the LimeSeg .jar does not show up in the plugins folder or is seen in the Plugins menu of FIJI (Plugins > LimeSeg).

After restarting FIJI the LimeSeg box is checked under the Manage Update Sites window. 

FIJI was reinstalled to its newest version. 

This was tested on two machines. Both are operating on Windows 10.

Looking forward to trying out LimeSeg on our 3D volumes!

Thank you,
Kyle

**Comment by NicoKiaru** [comment]
Have you looked far at he bottom of the Plugins menu ? Because that's where LimeSeg shows up. You can also access the function in the search bar `Sphere Seg`, or you can try if the examples scripts work in the script editor `File>New>Text Window` then `Templates>LimeSeg`.

Let me know!

**Comment by kdmarchuk** [comment]
Wow. Color my colleague and I both confused and embarrassed. We both could have sworn we looked all the way to the bottom.

Sorry for bothering you. Initial results look promising!

Best,
Kyle
